### ISSUE TITLE
There is no menu when i try to open

### ISSUE THREAD

**Issue by Brigante2288** [Messiah93/GWBot-SandfordFarmer#1]
When i try to run the script no menu appears asking for my character name or anything.

**Comment by Messiah93** [comment]
Is Autoit3 installed on your computer?

**Comment by Brigante2288** [comment]
Yes it is. When i try and run the .au3 no menu appears. I can see that the script is running in the backround but i cant actually activate it on a character.

**Comment by Messiah93** [comment]
It work like a charm on my computer... Have you tried with another BOT?

**Comment by Brigante2288** [comment]
Idk what I am doing wrong. I see that the script is working but i just dont see a menu. I basically cant enter my character name and pick a farm.

**Comment by Messiah93** [comment]
Try to re-install AutoIT3: https://www.autoitscript.com/cgi-bin/getfile.pl?autoit3/autoit-v3-setup.exe

**Comment by Brigante2288** [comment]
I just did the same exact thing. I run the script and nothing pops up. I check task manager and i see that its running in thr backround processes but I cant find a way to bring up the menu.

**Comment by Brigante2288** [comment]
Is there a way to add an icon to the system tray so i can force bring up the menu?

**Comment by Brigante2288** [comment]
Just figured something out. When i launch the bot without guild wars running the menu runs. When i launch it with guild wars running the menu does not appear. But if done this way the bot doesnt seem to actually work.

**Comment by Brigante2288** [comment]
Yup the menu does not appear if I am running GW. Menu does appear if I am not running GW but then the bot does not work at all.

**Comment by Messiah93** [comment]
I try to fix it today.

**Comment by Messiah93** [comment]
You can download last source code and try.

**Comment by Brigante2288** [comment]
It worked but now jm getting this error when the farm actually starts. 
![20210216_070427](https://user-images.githubusercontent.com/79122364/108060757-52315e00-7025-11eb-8135-397d49dee94f.jpg)

**Comment by Brigante2288** [comment]
Every farm is broken because of that error and the red iris flower one just doesnt work.

**Comment by Brigante2288** [comment]
Btw man thank you for fixing everything so fast. Hope you can figure this one out!

**Comment by Messiah93** [comment]
Fixed, download again.

**Comment by Brigante2288** [comment]
Works perfectly brother.

**Comment by Brigante2288** [comment]
Hey man i have another issue. The red iris flower farm just doesnt work. My character walks outside, runs right. Pauses in front of a rock and teles back every time. The bot says searching for flower-no flower found over and over again.

**Comment by Messiah93** [comment]
Try with the lastest source code.
