### ISSUE TITLE
stopped working

### ISSUE THREAD

**Issue by Rev0x** [Messiah93/GWBot-SandfordFarmer#2]
hey brother..used this about 6 months back but took a break from the game..came back a few days ago and the bot seems to not work anymore..menu loads up fine but when i choose my character and press start nothing happens

**Comment by Messiah93** [comment]
Hey, after each Guild Wars game update, all GW1 GWA2 bot library need to be updated. So just GWA2.au3 need to be updated. I'm not able to update GWA2 headers myself, but a big community on ElitePVP forum can do it. I don't know if GWA2 is updated to latest GW1 version, I will check it and I'll keep you informed. Bye.

**Comment by Messiah93** [comment]
Just updated, you can try latest version, just download bot again.
